on:
  push:
    branches:
    - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      # Check python code
      - uses: chartboost/ruff-action@v1
